"""ATK Connect examples reproduced from ~/codes/atk-doc.

The command lists are intentionally close to the source documentation so
each case can be compared against the original 二次开发案例.
"""
from __future__ import annotations

from common import ConnectCommand, ConnectExample

DOC_ROOT = "~/codes/atk-doc/02-案例教程/8-二次开发案例"

def c(command: str, param: str, note: str = "") -> ConnectCommand:
    return ConnectCommand(command=command, param=param, note=note)

SIMPLE = ConnectExample(
    key='simple',
    title='入门案例',
    source_doc=f"{DOC_ROOT}/1-入门案例.md",
    note="",
    commands=(
        c('New', '/ Scenario SimpleExample'),
        c('SetAnalysisTimePeriod', '* "2026-03-06 00:00:00.000" "2026-03-09 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite Satellite1'),
        c('SetState', '*/Satellite/Satellite1 Classical HPOP "2026-03-06 00:00:00.000" "2026-03-09 00:00:00.000" 60 ICRF "2026-03-06 00:00:00.000" 6878137.000 0 0 0 0 0'),
        c('Window2D', '/ Create'),
        c('Window3D', '/ CreateWindow Normal'),
        c('Animate', '* Reset'),
        c('Report_RM', '*/Satellite/Satellite1 Style "J2000 Position Velocity"  TimePeriod "2026-03-06 00:00:00.000" "2026-03-09 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

ACCESS = ConnectExample(
    key='access',
    title='可见性工具案例',
    source_doc=f"{DOC_ROOT}/2-可见性工具案例.md",
    note="",
    commands=(
        c('New', '/ Scenario AccessExample'),
        c('SetAnalysisTimePeriod', '* "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite Satellite1'),
        c('New', '/ Satellite Satellite2'),
        c('SetState', '*/Satellite/Satellite1 Classical HPOP "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000" 60 ICRF "2023-03-11 00:00:00.000" 6878137.000 0 45 0 0 0'),
        c('SetConstraint', '*/Satellite/Satellite1 AzimuthAngle Min 0 Max 180'),
        c('SetConstraint', '*/Satellite/Satellite1 ElevationAngle Min -45 Max 45'),
        c('SetConstraint', '*/Satellite/Satellite1 LineOfSight On'),
        c('Animate', '* Start'),
        c('Animate', '* Reset'),
        c('Access', '*/Satellite/Satellite1 */Satellite/Satellite2 TimePeriod "2023-03-11 00:00:00.000" "2023-03-11 11:00:00.000"'),
        c('Access_RM', '*/Satellite/Satellite1 Access Compute "Access" "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

COVERAGE = ConnectExample(
    key='coverage',
    title='覆盖工具案例',
    source_doc=f"{DOC_ROOT}/3-覆盖工具案例.md",
    note="",
    commands=(
        c('New', '/ Scenario CoverageExample'),
        c('SetAnalysisTimePeriod', '* "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite Satellite1'),
        c('OrbitWizard', '*/Satellite/Satellite1 RepeatingGroundTrace Color Yellow TimePeriod "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000" ApproxAltitude 500000 Inclination 45 RevsToRepeat 10 LongitudeFirstAN 0'),
        c('New', '/ */Satellite/Satellite1/Sensor Sensor1'),
        c('Define', '*/Satellite/Satellite1/Sensor/Sensor1 SimpleCone 50'),
        c('New', '/ Facility Facility1'),
        c('SetPosition', '*/Facility/Facility1 Geodetic 30 110 0.0'),
        c('Animate', '* Start'),
        c('Animate', '* Reset'),
        c('Cov', '*/Facility/Facility1 Asset */Satellite/Satellite1/Sensor/Sensor1 Assign'),
        c('Cov', '*/Satellite/Satellite1/Sensor/Sensor1 Access Compute "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000"'),
        c('Cov_RM', '*/Facility/Facility1 Access Compute "Coverage" "2023-03-11 00:00:00.000" "2023-03-12 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

HOHMANN_TRANSFER = ConnectExample(
    key='hohmann_transfer',
    title='霍曼转移',
    source_doc=f"{DOC_ROOT}/4-轨道机动规划工具案例/4.1-霍曼转移.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario HohmannTransfer'),
        c('SetAnalysisTimePeriod', '* "5 Nov 2022 00:00:00.000" "7 Nov 2022 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite HohmannTransfer'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetProp'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.Target_Sequence.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.Target_Sequence1.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/HohmannTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Epoch 5 Nov 2022 00:00:00.000 UTCG'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.CoordinateSystem "CentralBody/Earth J2000"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.CoordinateType "Keplerian"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.sma 6700 km'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.ecc 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.inc 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.RAAN 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.w 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.TA 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.SegmentColor -16776961'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate.StoppingConditions.Duration.TripValue 7200 sec'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.SegmentColor 4278212095'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.Results "Radius Of Apoapsis"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/HohmannTransfer VNC"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/HohmannTransfer AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.Results "Radius Of Apoapsis"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Active true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Desired 42238 km'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Tolerance 100 m'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Scale 1 m'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Weight 1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.SegmentColor -16711936'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate1.StoppingConditions Apoapsis'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.SegmentColor 4278212095'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.Results "Eccentricity"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/HohmannTransfer VNC"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/HohmannTransfer AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.Results "Eccentricity"'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Active true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Desired 0'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Tolerance 0.001'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Scale 1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Weight 1'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.SegmentColor -65536'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/HohmannTransfer SetValue MainSequence.SegmentList.Propagate2.StoppingConditions.Duration.TripValue 172800 sec'),
        c('Astrogator', '*/Satellite/HohmannTransfer RunMCS'),
        c('Animate', '* Reset'),
        c('Astrogator', '*/Satellite/HohmannTransfer ApplyAllProfileChanges'),
        c('Report_RM', '*/Satellite/HohmannTransfer Style "Position" TimePeriod "5 Nov 2022 00:00:00.000" "7 Nov 2022 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

LEO_TO_GEO_TRANSFER = ConnectExample(
    key='leo_to_geo_transfer',
    title='LEO 到 GEO 快速转移轨道',
    source_doc=f"{DOC_ROOT}/4-轨道机动规划工具案例/4.2-LEO到GEO快速转移轨道.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario FastTransfer'),
        c('SetAnalysisTimePeriod', '* "5 Nov 2022 00:00:00.000" "7 Nov 2022 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite FastTransfer'),
        c('Astrogator', '*/Satellite/FastTransfer SetProp'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.Target_Sequence.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.Target_Sequence1.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/FastTransfer InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Epoch 5 Nov 2022 00:00:00.000 UTCG'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.CoordinateSystem "CentralBody/Earth J2000"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.CoordinateType "Keplerian"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.sma 6700 km'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.ecc 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.inc 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.RAAN 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.w 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.TA 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.SegmentColor -16776961'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate.StoppingConditions.Duration.TripValue 7200 sec'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.SegmentColor 4278212095'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.Results "Radius Of Apoapsis"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/FastTransfer VNC"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/FastTransfer AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.Results "Radius Of Apoapsis"'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Active true'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Desired 84328394 m'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Tolerance 100 m'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Scale 1 m'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver StateCalcRadiusOfApoapsis Weight 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.SegmentColor -16711936'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.StoppingConditions RMagnitude'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate1.StoppingConditions.RMagnitude.TripValue 42164197 m'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.SegmentColor 4278212095'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.Results "Eccentricity"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/FastTransfer VNC"'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/FastTransfer AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/FastTransfer AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.Z'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 300'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Z Active true'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Z MaxStep 300'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Z Pert 0.1'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Z Scale 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.Results "Eccentricity"'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Active true'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Desired 0'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Tolerance 0.001'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Scale 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver StateCalcEccentricity Weight 1'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.SegmentColor -65536'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/FastTransfer SetValue MainSequence.SegmentList.Propagate2.StoppingConditions.Duration.TripValue 172800 sec'),
        c('Astrogator', '*/Satellite/FastTransfer RunMCS'),
        c('Animate', '* Reset'),
        c('Astrogator', '*/Satellite/FastTransfer ApplyAllProfileChanges'),
        c('Report_RM', '*/Satellite/FastTransfer Style "Position" TimePeriod "5 Nov 2022 00:00:00.000" "7 Nov 2022 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

INCLINATION_TARGETING = ConnectExample(
    key='inclination_targeting',
    title='倾角改变与瞄准轨道',
    source_doc=f"{DOC_ROOT}/4-轨道机动规划工具案例/4.3-倾角改变与瞄准轨道.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario InclinationChange'),
        c('SetAnalysisTimePeriod', '* "2022-11-05 00:00:00.000000" "2022-11-08 00:00:00.000000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite SatInclinationChange'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetProp'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.Target_Sequence.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.Target_Sequence1.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.Target_Sequence2.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/SatInclinationChange InsertSegment MainSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.CoordinateSystem "CentralBody/Earth J2000"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.CoordinateType "Keplerian"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.sma 6570 km'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.ecc 0'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.inc 28 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.RAAN 0 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.w 0 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.TA 0 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.InitialState.Epoch "2022-11-05 00:00:00.000" UTCG'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.SegmentColor 255000000'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.Drag.AtmModel NRLMSISE00'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Moon.GravModel PointMass'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.StoppingConditions.Duration.TripValue 7200 sec'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.StoppingConditions.Duration.Tolerance 0.0001 sec'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.MnvrType Impulsive'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/SatInclinationChange VNC(Earth)"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/SatInclinationChange AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.SegmentList.Maneuver.Results "Radius Of Apoapsis"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver "StateCalcRadiusOfApoapsis" Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver "StateCalcRadiusOfApoapsis" Desired 42160000 m'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver "StateCalcRadiusOfApoapsis" Tolerance 0.1 m'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver "StateCalcRadiusOfApoapsis" Scale 1 m'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence.Profiles.Differential_Corrector Maneuver "StateCalcRadiusOfApoapsis" Weight 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.SegmentColor 4294902015'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.Drag.AtmModel NRLMSISE00'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ForceModel.ThirdBodies.Moon.GravModel PointMass'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.SegmentColor 4294902015'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.StoppingConditions Apoapsis'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.StoppingConditions.Apoapsis.RepeatCount 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.StoppingConditions.Apoapsis.Tolerance 0.0001'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.SegmentColor -256'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.MnvrType Impulsive'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/SatInclinationChange VNC(Earth)"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/SatInclinationChange AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.SegmentList.Maneuver.Results "Eccentricity"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Tolerance 0.001'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Scale 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Weight 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence1.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Desired 0'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver.SegmentColor 4278190335'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.Drag.AtmModel NRLMSISE00'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ForceModel.ThirdBodies.Moon.GravModel PointMass'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.StoppingConditions AscendingNode'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.StoppingConditions.AscendingNode.RepeatCount 2'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.StoppingConditions.AscendingNode.Tolerance 0.0001'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver.MnvrType Impulsive'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/SatInclinationChange VNC(Earth)"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/SatInclinationChange AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/SatInclinationChange AddMCSSegmentControl MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.Y'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.SegmentList.Maneuver.Results "Inclination" "Eccentricity"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X MaxStep 100 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Pert 0.1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Scale 1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Y Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Y MaxStep 100 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Y Pert 0.1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSControlValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.Y Scale 1 m/s'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcInclination" Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcInclination" Tolerance 0 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcInclination" Scale 1 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcInclination" Weight 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcInclination" Desired 0 deg'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Active true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Tolerance 0.001'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Scale 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Weight 1'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetMCSConstraintValue MainSequence.SegmentList.Target_Sequence2.Profiles.Differential_Corrector Maneuver "StateCalcEccentricity" Desired 0'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.Drag.UseDrag true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.Drag.AtmModel NRLMSISE00'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ForceModel.ThirdBodies.Moon.GravModel PointMass'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.StoppingConditions Duration'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.StoppingConditions.Duration.TripValue 129600 sec'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.StoppingConditions.Duration.Tolerance 0.0001 sec'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Initial_State.ComponentName "28 deg Inclined Orbit"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate.ComponentName "Propagate 2 hours"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence.ComponentName "Begin Hohmann"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate1.ComponentName "To Apogee"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence1.ComponentName "Finish Hohmann"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate2.ComponentName "To Ascending Node"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Target_Sequence2.ComponentName "Simple Plane Change"'),
        c('Astrogator', '*/Satellite/SatInclinationChange SetValue MainSequence.SegmentList.Propagate3.ComponentName "Propagate 36 hours"'),
        c('Astrogator', '*/Satellite/SatInclinationChange RunMCS'),
        c('Animate', '* Reset'),
        c('Astrogator', '*/Satellite/SatInclinationChange ApplyAllProfileChanges'),
        c('Report_RM', '*/Satellite/SatInclinationChange Style "Position" TimePeriod "5 Nov 2022 00:00:00.000" "8 Nov 2022 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

FREE_RETURN_LUNAR_TRANSFER = ConnectExample(
    key='free_return_lunar_transfer',
    title='基于自由返回轨道的地月转移',
    source_doc=f"{DOC_ROOT}/4-轨道机动规划工具案例/4.4基于自由返回轨道的地月转移.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario exLunarFreeReturn'),
        c('SetAnalysisTimePeriod', '* "2028-06-24 16:24:55.000" "2028-06-30 02:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite exLunarFreeReturn'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetProp'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn DeleteSegment MainSequence.SegmentList.InitialState'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn InsertSegment MainSequence.SegmentList.- Target_Sequence'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn InsertSegment MainSequence.SegmentList.TargetSequence.SegmentList.- InitialState'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.CoordinateSystem "CentralBody/Earth J2000"'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.CoordinateType "Keplerian"'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.sma 6548151 m'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.ecc 0'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.inc 21'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.RAAN 149'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.w 0'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Keplerian.TA 199'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.InitialState.InitialState.Epoch "24 Jun 2028 16:25:59.184" UTCG'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn InsertSegment MainSequence.SegmentList.TargetSequence.SegmentList.- Maneuver'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.MnvrType Impulsive'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.ImpulsiveMnvr.ThrustAxes "Satellite/exLunarFreeReturn VNC"'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.ImpulsiveMnvr.CoordType Cartesian'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.ImpulsiveMnvr.Cartesian.X 3160'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.ImpulsiveMnvr.Cartesian.Y 0'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver.ImpulsiveMnvr.Cartesian.Z 0'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn InsertSegment MainSequence.SegmentList.TargetSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.Gravity.GravModel WGS84'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.Drag.UseDrag false'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.StoppingConditions Periapsis'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.StoppingConditions.Periapsis.CalcObjectAttributes.CentralBody Moon'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.StoppingConditions.Periapsis.RepeatCount 1'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn InsertSegment MainSequence.SegmentList.TargetSequence.SegmentList.- Propagate'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.CentralBodyCode 2'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.ForceModel.Gravity.GravModel JGM3'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.ForceModel.Gravity.MaxDegree 20'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.ForceModel.Gravity.MaxOrder 20'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.ForceModel.Drag.UseDrag false'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.ForceModel.SRP.UseSRP true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Moon.UseGravity true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.ForceModel.ThirdBodies.Sun.UseGravity true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.StoppingConditions Periapsis'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.StoppingConditions.Periapsis.CalcObjectAttributes.CentralBody Earth'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.StoppingConditions.Periapsis.RepeatCount 1'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn AddMCSSegmentControl MainSequence.SegmentList.TargetSequence.SegmentList.InitialState InitialState.Keplerian.RAAN'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn AddMCSSegmentControl MainSequence.SegmentList.TargetSequence.SegmentList.InitialState InitialState.Epoch'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn AddMCSSegmentControl MainSequence.SegmentList.TargetSequence.SegmentList.Maneuver ImpulsiveMnvr.Cartesian.X'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.Results "AltitudeOfPeriapsis"'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate.Results.StateCalcAltitudeOfPeriapsis.CentralBody Moon'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.Results "AltitudeOfPeriapsis" "Inclination"'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.Results.StateCalcAltitudeOfPeriapsis.CentralBody Earth'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.SegmentList.Propagate1.Results.StateCalcInclination.CentralBody Earth'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetValue MainSequence.SegmentList.TargetSequence.Profiles Differential_Corrector'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSControlValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Maneuver ImpulsiveMnvr.Cartesian.X Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSControlValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector InitialState InitialState.Epoch Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSControlValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector InitialState InitialState.Keplerian.RAAN Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate "StateCalcAltitudeOfPeriapsis" Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate "StateCalcAltitudeOfPeriapsis" Desired 100000 m'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate "StateCalcAltitudeOfPeriapsis" Tolerance 100 m'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcAltitudeOfPeriapsis" Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcAltitudeOfPeriapsis" Desired 50000 m'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcAltitudeOfPeriapsis" Tolerance 100 m'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcInclination" Active true'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcInclination" Desired 43 deg'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn SetMCSConstraintValue MainSequence.SegmentList.TargetSequence.Profiles.Differential_Corrector Propagate1 "StateCalcInclination" Tolerance 0.1 deg'),
        c('Astrogator', '*/Satellite/exLunarFreeReturn RunMCS'),
        c('Animate', '* Reset'),
        c('Save', '/ *'),
    ),
)

HUGE_CONSTELLATION = ConnectExample(
    key='huge_constellation',
    title='巨型星座设计案例',
    source_doc=f"{DOC_ROOT}/9-巨型星座设计案例.md",
    note="",
    commands=(
        c('New', '/ Scenario HugeConstellation'),
        c('SetAnalysisTimePeriod', '* "2024-03-18 00:00:00.000" "2024-03-19 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite Satellite1'),
        c('WalkerDelta', '*/Satellite/Satellite1 Semimajoraxis 6678137 Eccentricity 0 Inclination 65 RAAN 0 ArgumentOfPerigee 180 TrueAnomaly 180 NumPlanes 30 NumSatsPerPlane 10 InterPlanePhaseIncrement 1 RAANSpread 360 ColorByPlane Yes Yes'),
        c('Animate', '* Start'),
        c('Animate', '* Reset'),
        c('Save', '/ *'),
    ),
)

RPO_TEARDROP = ConnectExample(
    key='rpo_teardrop',
    title='RPO 水滴绕飞案例',
    source_doc=f"{DOC_ROOT}/12-RPO案例.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario Teardrop'),
        c('SetAnalysisTimePeriod', '* "2007-03-08 00:00:00.000" "2007-03-13 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite WorkSatellite'),
        c('SetState', '*/Satellite/WorkSatellite Classical HPOP "2007-03-08 00:00:00.000" "2007-03-13 00:00:00.000" 60 J2000 "2007-03-08 00:00:00.000" 42164000 0 0 0 0 0'),
        c('New', '/ Satellite ServiceSatellite'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetProp'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.sma 6700000 m'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.ecc 0'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.inc 0'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.RAAN 0'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.w 0'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.Initial_State.InitialState.Keplerian.TA 0'),
        c('Astrogator', '*/Satellite/ServiceSatellite InsertSegment MainSequence.SegmentList.- RPOTearDrop'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.CenterBody "Earth"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.GravityModel "WGS84"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.ThreeBodyGravity "Sun, Moon"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.ThreeBodyModel "Point-Mass Model"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.AtmosphericDrag "On"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.AtmosphericModel "NRLMSISE00"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.SolarPressure "On"'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.NumCircles 5'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.StartDistance -300'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.ManeuverDistance -800'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.WaitTime 21600'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.MaxDeltaTrueAnomaly 5'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.SolveMethod 2'),
        c('Reference', '*/Satellite/ServiceSatellite SetRefSatellite */Satellite/WorkSatellite'),
        c('Astrogator', '*/Satellite/ServiceSatellite SetValue MainSequence.SegmentList.RPOTearDrop.Reference "Satellite/WorkSatellite"'),
        c('Astrogator', '*/Satellite/ServiceSatellite RunMCS'),
        c('Animate', '* Reset'),
        c('Astrogator', '*/Satellite/ServiceSatellite ApplyAllProfileChanges'),
        c('Report_RM', '*/Satellite/ServiceSatellite Style "Position" TimePeriod "8 Mar 2007 00:00:00.000" "13 Mar 2007 00:00:00.000"'),
        c('Save', '/ *'),
    ),
)

LAUNCH_WINDOW_CLOSE_APPROACH = ConnectExample(
    key='launch_window_close_approach',
    title='发射窗口接近分析案例（文档仅提供场景/火箭导入命令）',
    source_doc=f"{DOC_ROOT}/16-发射窗口接近分析.md",
    note="文档说明发射窗口接近分析 Connect 命令暂未完成开发；本案例仅复现已给出的场景和火箭导入命令。",
    commands=(
        c('New', '/ Scenario LaunchWindowAnalysis'),
        c('SetAnalysisTimePeriod', '* "13 Feb 2023 00:00:00.000" "18 Feb 2023 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ LaunchVehicle LaunchVehicle1'),
        c('SetState', '*/LaunchVehicle/LaunchVehicle1 FromFile "(ATK根目录)\\Help\\Examples\\08-二次开发案例\\LaunchVehicle.e"'),
    ),
)

ADVANCED_CLOSE_APPROACH = ConnectExample(
    key='advanced_close_approach',
    title='高级接近分析案例',
    source_doc=f"{DOC_ROOT}/17-高级接近分析.md",
    note="长案例可能依赖 ATK Astrogator / 接近分析等授权模块；若出现 NACK，请对照失败命令和文档修正。",
    commands=(
        c('New', '/ Scenario AdvancedProximityAnalysis'),
        c('SetAnalysisTimePeriod', '* "13 Feb 2023 00:00:00.000" "18 Feb 2023 00:00:00.000"'),
        c('Animate', '* Reset'),
        c('New', '/ Satellite Satellite1'),
        c('SetState', '*/Satellite/Satellite1 Classical HPOP "13 Feb 2023 00:00:00.000" "18 Feb 2023 00:00:00.000" 60 ICRF "13 Feb 2023 00:00:00.000" 7000137 0.01 28.5 0 0 0'),
        c('Animate', '* Reset'),
        c('New', '/ AdvCat AdvCat1'),
        c('ACAT', '*/AdvCat/AdvCat1 Primary Add "Satellite/Satellite1" Fixed 21000.0 11000.0 6000.0 HardBodyRadius 2'),
        c('ACAT', '*/AdvCat/AdvCat1 Secondary Add "(ATK根目录)\\Help\\Examples\\08-二次开发案例\\TLE20230212.txt" Fixed 10000.0 5000.0 3000.0'),
        c('ACAT', '*/AdvCat/AdvCat1 PreFilters OutOfDate On'),
        c('ACAT', '*/AdvCat/AdvCat1 PreFilters ApogeePerigee 60000.0'),
        c('ACAT', '*/AdvCat/AdvCat1 PreFilters OrbitPath Off'),
        c('ACAT', '*/AdvCat/AdvCat1 PreFilters Time On'),
        c('ACAT', '*/AdvCat/AdvCat1 Compute On'),
        c('Animate', '* Reset'),
        c('Report_RM', '*/AdvCat/AdvCat1 Style "Cat Event Message"'),
        c('Save', '/ *'),
    ),
)

EXAMPLES = (
    SIMPLE,
    ACCESS,
    COVERAGE,
    HOHMANN_TRANSFER,
    LEO_TO_GEO_TRANSFER,
    INCLINATION_TARGETING,
    FREE_RETURN_LUNAR_TRANSFER,
    HUGE_CONSTELLATION,
    RPO_TEARDROP,
    LAUNCH_WINDOW_CLOSE_APPROACH,
    ADVANCED_CLOSE_APPROACH,
)

EXAMPLE_BY_KEY = {example.key: example for example in EXAMPLES}
